services:
  mlflow:
    image: python:3.10-slim
    working_dir: /app
    command: bash -lc "pip install mlflow && mlflow ui --host 0.0.0.0 --port 5000"
    volumes:
      - ./:/app
    ports:
      - "5001:5000"
    networks:
      - mlflow-network

  api:
    build: .
    volumes:
      - ./artifacts:/app/artifacts
    ports:
      - "8001:8000"
    depends_on:
      - mlflow
    networks:
      - mlflow-network
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - mlflow-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    env_file:
      - .env
    networks:
      - mlflow-network
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:


networks:
  mlflow-network:
    driver: bridge
